version: "3"

services:
  postgres:
    image: postgres
    container_name: "test_postgres"
    env_file:
      - .env.test
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 2s
      timeout: 2s
      retries: 10
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/test_pgdata:/var/lib/postgresql/data
